package com.xxxsarutahikoxxx.kotlin.janglish.classifier


object Target1900 : Classifier {
    override fun contains(spell: String): Boolean = spell in VocabularyList

    val VocabularyList : List<String> = """
        improve
        relate
        provide
        consider
        include
        concern
        involve
        produce
        allow
        require
        appear
        tend
        agree
        describe
        add
        depend
        encourage
        exist
        reduce
        adapt
        compare
        increase
        suggest
        cost
        share
        wonder
        argue
        realize
        control
        affect
        find
        notice
        avoid
        force
        offer
        demand
        claim
        deal
        store
        complete
        value
        benefit
        opportunity
        quality
        author
        technology
        environment
        view
        situation
        effect
        influence
        term
        skill
        theory
        issue
        subject
        article
        statement
        experiment
        figure
        evidence
        industry
        economy
        medicine
        matter
        material
        species
        practice
        focus
        memory
        right
        accord
        thought
        interest
        account
        cause
        sound
        individual
        certain
        possible
        likely
        available
        social
        public
        physical
        scientific
        common
        general
        particular
        similar
        various
        native
        patient
        recent
        even
        yet
        rather
        instead
        simultaneously
        each
        challenge
        determine
        manage
        maintain
        refer
        approach
        advance
        express
        spread
        occur
        observe
        recognize
        suppose
        regard
        treat
        search
        prove
        establish
        mention
        represent
        prefer
        apply
        seek
        publish
        perform
        gain
        fit
        contain
        supply
        prepare
        bear
        prevent
        object
        decline
        replace
        connect
        attend
        survive
        respect
        waste
        advantage
        resource
        medium
        method
        attitude
        structure
        function
        feature
        aspect
        content
        detail
        range
        region
        trade
        habit
        cell
        fuel
        bill
        charge
        fine
        temperature
        decade
        emotion
        explanation
        solution
        degree
        access
        contrast
        status
        surface
        conflict
        audience
        clay
        epoch
        profit
        income
        ancestor
        crop
        significant
        necessary
        appropriate
        correct
        worth
        positive
        plastic
        political
        official
        private
        ancient
        due
        complex
        mobile
        blank
        male
        therefore
        thus
        eventually
        otherwise
        despite
        both
        succeed
        identify
        reflect
        assume
        estimate
        define
        indicate
        reveal
        attempt
        respond
        associate
        examine
        address
        trust
        doubt
        ignore
        refuse
        complain
        decrease
        vary
        emerge
        match
        stick
        hide
        attract
        promote
        satisfy
        earn
        preserve
        enable
        destroy
        tear
        suffer
        survey
        divide
        conduct
        graduate
        contribute
        desire
        relax
        target
        aim
        principle
        norm
        strategy
        track
        progress
        personality
        characteristic
        manner
        device
        origin
        gene
        atmosphere
        trend
        phenomenon
        context
        circumstance
        pain
        struggle
        pollution
        threat
        disaster
        consequence
        revolution
        majority
        mass
        stock
        wealth
        literature
        authority
        institution
        custom
        sight
        display
        colleague
        resident
        vehicle
        essential
        aware
        mental
        academic
        ordinary
        familiar
        novel
        specific
        chemical
        financial
        active
        negative
        direct
        obvious
        current
        urban
        furthermore
        likewise
        though
        nevertheless
        thereby
        hence
        appreciate
        admit
        predict
        acquire
        adopt
        purchase
        afford
        consume
        remove
        suit
        expand
        extend
        explore
        judge
        demonstrate
        insist
        appeal
        convince
        settle
        aid
        educate
        engage
        combine
        organize
        operate
        recall
        rely
        amaze
        confuse
        blame
        criticize
        behave
        encounter
        select
        flow
        evolve
        freeze
        release
        locate
        advertise
        imagination
        perspective
        confidence
        achievement
        reward
        corporation
        capital
        client
        crisis
        harm
        victim
        option
        campaign
        court
        code
        criminal
        agriculture
        religion
        philosophy
        conference
        document
        statistics
        analysis
        hypothesis
        notion
        stereotype
        review
        vocabulary
        organ
        gender
        fossil
        glacier
        laboratory
        virus
        occasion
        minister
        presence
        substance
        creative
        potential
        independent
        willing
        efficient
        ideal
        genetic
        entire
        relative
        extreme
        vast
        tiny
        desert
        rural
        previous
        legal
        nowadays
        seldom
        meanwhile
        latter
        versus
        all
        perceive
        expect
        intend
        request
        remind
        inspire
        fascinate
        emphasize
        recommend
        propose
        distinguish
        complicate
        transform
        credit
        reserve
        oppose
        deny
        reject
        ban
        frighten
        participate
        compete
        outcome
        arise
        generate
        obtain
        employ
        import
        handle
        repair
        cure
        transport
        deliver
        rush
        commit
        hate
        regret
        consist
        translate
        conclude
        comfort
        facility
        trait
        humanity
        tribe
        elite
        lawyer
        category
        version
        diversity
        proportion
        instrument
        innovation
        weapon
        dialect
        barrier
        myth
        ritual
        routine
        emergency
        alarm
        harvest
        grain
        quantity
        budget
        expense
        insurance
        loan
        contract
        mammal
        infant
        protein
        tissue
        fault
        neighborhood
        vote
        duty
        psychology
        intelligent
        conscious
        cognitive
        sensitive
        accurate
        strict
        severe
        actual
        visual
        false
        illegal
        violent
        military
        civil
        typical
        universal
        constant
        fundamental
        primary
        rare
        convenient
        enormous
        concentrate
        investigate
        adjust
        arrange
        alter
        confirm
        absorb
        expose
        transfer
        abandon
        injure
        recover
        praise
        favor
        celebrate
        guarantee
        ensure
        award
        grant
        pernit
        disappoint
        embarrass
        bother
        upset
        inform
        warn
        command
        imply
        pretend
        interpret
        react
        interact
        differ
        breathe
        stare
        breed
        melt
        invest
        manufacture
        construct
        wisdom
        insight
        discipline
        habitat
        territory
        colony
        district
        shelter
        landscape
        inhabitant
        depression
        nerve
        wound
        symptom
        therapy
        welfare
        incident
        witness
        glance
        ray
        ingredient
        agent
        fee
        sacrifice
        burden
        layer
        row
        instruction
        editor
        stuff
        mission
        procedure
        immigration
        hybrid
        opponent
        outcome
        equality
        reputation
        capable
        proper
        sufficient
        reasonable
        linguistic
        verbal
        bilingual
        contemporary
        conventional
        overall
        widespread
        domestic
        distant
        nuclear
        thick
        contrary
        virtual
        aggressive
        evil
        elemental
        annual
        immediate
        admire
        approve
        devote
        pursue
        dominate
        possess
        occupy
        secure
        capture
        lend
        rent
        persuade
        urge
        stimulate
        annoy
        scare
        crash
        collapse
        remark
        illustrate
        protest
        declare
        isolate
        accompany
        surround
        endanger
        exhaust
        disturb
        puzzle
        quit
        cope
        enhance
        ease
        apologize
        acknowledge
        resemble
        swallow
        distribute
        export
        launch
        justice
        courage
        passion
        bond
        companion
        mood
        prejudice
        discrimination
        priority
        globe
        hemisphere
        boundary
        asteroid
        gravity
        component
        liquid
        orbit
        trace
        treasure
        logic
        council
        profession
        secretary
        jury
        physician
        surgeon
        guard
        license
        grocery
        litter
        drought
        blaze
        trap
        fate
        luxury
        exception
        sum
        conservation
        democratic
        numerous
        minor
        superior
        principal
        crucial
        vital
        rational
        anxious
        curious
        rude
        remote
        tropical
        marine
        extraordinary
        odd
        biological
        racial
        initial
        distinct
        pure
        exact
        sustain
        defend
        foster
        pile
        attach
        pour
        load
        stretch
        convey
        derive
        tap
        calculate
        suspect
        detect
        attribute
        evaluate
        accuse
        sue
        retire
        shrink
        bow
        peer
        delight
        relieve
        discourage
        frustrate
        neglect
        resist
        restrict
        eliminate
        beat
        defeat
        punish
        prohibit
        deserve
        pose
        fold
        monitor
        specialize
        accomplish
        faith
        ambition
        enthusiasm
        honor
        discount
        fare
        frame
        mode
        architecture
        sequence
        usage
        abuse
        pesticide
        pollen
        prefecture
        geography
        administration
        candidate
        rubbish
        bias
        vice
        debt
        prospect
        expedition
        session
        semester
        reef
        mineral
        sibling
        proverb
        instinct
        minimum
        millennium
        donor
        herd
        league
        cooperation
        fairy
        precise
        intense
        solid
        permanent
        brief
        flexible
        informal
        temporary
        frequent
        visible
        external
        internal
        plain
        modest
        equivalent
        incredible
        guilty
        raw
        manual
        literary
        artificial
        sophisticated
        polish
        embrace
        compose
        imitate
        yield
        exhibit
        impress
        overwhelm
        interrupt
        endure
        confront
        consult
        bump
        dispute
        negotiate
        justify
        resolve
        reverse
        convert
        impose
        govern
        esteem
        assist
        rescue
        entertain
        ruin
        bury
        owe
        chew
        bend
        quote
        classify
        seal
        arrest
        substitute
        retain
        restore
        float
        leap
        blossom
        merit
        faculty
        charm
        nutrition
        beverage
        recipe
        molecule
        ecology
        ethics
        mankind
        nationality
        pension
        scheme
        haven
        formation
        skeleton
        core
        stem
        span
        limitation
        obstacle
        province
        galaxy
        sensation
        sympathy
        pity
        tragedy
        divorce
        theft
        panic
        retreat
        jail
        blade
        stroke
        clue
        queue
        enterprise
        fortune
        stable
        steady
        mature
        eager
        reluctant
        humorous
        fluent
        prime
        precious
        artistic
        ethnic
        primitive
        federal
        royal
        mutual
        apparent
        casual
        slight
        mere
        spare
        abstract
        ultimate
        venture
        chase
        migrate
        flee
        swing
        hesitate
        postpone
        withdraw
        grip
        grab
        grasp
        gaze
        scan
        forecast
        register
        advocate
        trigger
        cultivate
        qualify
        interfere
        clog
        distract
        forbid
        deceive
        overlook
        dismiss
        spoil
        yawn
        greet
        nod
        obey
        undergo
        rear
        heal
        cite
        modify
        exaggerate
        burst
        thrill
        exceed
        privilege
        liberty
        prosperity
        heritage
        congress
        parliament
        infrastructure
        dimension
        portion
        supplement
        appetite
        temper
        fancy
        illusion
        fatigue
        stress
        hazard
        infection
        famine
        chaos
        distress
        shame
        cattle
        predator
        wilderness
        shade
        monk
        priest
        funeral
        transition
        circulation
        adolescent
        equation
        patent
        metaphor
        narrative
        consent
        dignity
        relevant
        adequate
        genuine
        prompt
        intimate
        alert
        conservative
        indifferent
        alien
        random
        subtle
        modify
        multiple
        polar
        arctic
        acid
        cosmetic
        extinct
        spiritual
        meaningful
        mechanical
        dynamic
        boost
        reinforce
        accumulate
        nurture
        accustom
        correspond
        assign
        regulate
        violate
        irritate
        insult
        diminish
        exclude
        rob
        deprive
        deposit
        twist
        blend
        mount
        pitch
        cast
        dump
        anticipate
        assess
        pronounce
        spell
        portray
        astonish
        emit
        cough
        wander
        drift
        cease
        underlie
        constitute
        resort
        decorate
        reform
        conquer
        persist
        incentive
        intuition
        impulse
        fantasy
        destiny
        virtue
        compliment
        anniversary
        hive
        nursery
        dormitory
        gallery
        mill
        output
        joint
        phase
        particle
        column
        margin
        crack
        mess
        spectator
        prey
        irrigation
        fluid
        prairie
        estate
        plot
        realm
        deadline
        poll
        census
        controversy
        combat
        consensus
        treaty
        remedy
        triumph
        competent
        brilliant
        sensible
        generous
        brave
        optimistic
        passive
        harsh
        ugly
        sensory
        oral
        awkward
        neutral
        vague
        urgent
        inevitable
        concrete
        abundant
        sacred
        prominent
        dense
        profound
        tackle
        dedicate
        dare
        accelerate
        transmit
        strain
        tempt
        amuse
        disgust
        cheat
        confine
        conceal
        forgive
        discard
        convict
        commute
        whisper
        fade
        starve
        vanish
        drain
        dip
        crush
        explode
        terrify
        exploit
        elect
        equip
        fulfill
        log
        inherit
        submit
        renew
        reproduce
        flourish
        thrive
        spill
        scatter
        sprawl
        prevail
        intellect
        courtesy
        posture
        sociology
        motive
        cue
        utility
        chore
        cereal
        fiber
        intake
        scent
        flavor
        mixture
        ratio
        counterpart
        patch
        flock
        pedestrian
        librarian
        draft
        formula
        commodity
        asset
        currency
        tide
        abortion
        toll
        penalty
        deforestation
        microbe
        outbreak
        epidemic
        syndrome
        outlet
        perfume
        reception
        recipient
        keen
        decent
        mild
        humble
        noble
        selfish
        cruel
        ridiculous
        deaf
        grateful
        elaborate
        rough
        bitter
        radical
        collective
        exotic
        steep
        shallow
        parallel
        probable
        absolute
        aesthetic
        proceed
        bloom
        assert
        bet
        boast
        beg
        compromise
        inquire
        yell
        bully
        descend
        crawl
        lean
        spin
        drown
        split
        revive
        sigh
        refrain
        sweep
        knit
        cram
        digest
        suppress
        offend
        compensate
        compound
        comprise
        transplant
        uncover
        extract
        recruit
        entitle
        appoint
        install
        enforce
        implement
        manipulate
        refine
        attain
        quest
        outlook
        premise
        unity
        fabric
        thread
        craftsman
        sculpture
        sphere
        curve
        profile
        fingerprint
        criterion
        altitude
        tuition
        stake
        acquaintance
        discourse
        gratitude
        worship
        caution
        horror
        decay
        defect
        troop
        grave
        ranch
        republic
        county
        cottage
        commerce
        recession
        despair
        spray
        compassion
        offspring
        cortex
        fame
        worthwhile
        valid
        thorough
        tremendous
        empirical
        secondary
        subsequent
        innate
        interior
        bare
        innocent
        delicate
        ambiguous
        fragile
        awful
        inferior
        ashamed
        medieval
        stern
        tense
        imperial
        magnificent
        integrate
        incorporate
        utilize
        revise
        prolong
        lessen
        stir
        drag
        scrub
        strip
        squeeze
        shed
        plug
        distort
        disrupt
        devastate
        worsen
        abolish
        regain
        exert
        precede
        lag
        converse
        utter
        outline
        conform
        designate
        assure
        reassure
        console
        induce
        oblige
        compel
        provoke
        bathe
        bleed
        cruise
        soar
        symbolize
        comprehend
        protocol
        domain
        index
        transaction
        fragment
        fraction
        bug
        germ
        diagnosis
        obsession
        nightmare
        paradox
        irony
        sorrow
        maximum
        excess
        frontier
        refuge
        timber
        slavery
        hierarchy
        bureau
        supervisor
        spouse
        rebel
        pastime
        feast
        basin
        sewage
        scenery
        tomb
        landmark
        monument
        flesh
        garment
        glimpse
        glow
        grace
        sincere
        bold
        tame
        vulnerable
        naked
        immune
        chronic
        gradual
        scarce
        toxic
        accidental
        irrelevent
        trivial
        indispensable
        indigenous
        prehistoric
        holy
        retail
        metropolitan
        straightforward
        vivid
        outstanding
        enrich
        undertake
        accommodate
        assemble
        embody
        weave
        retrieve
        clap
        scratch
        erase
        sew
        cling
        resign
        startle
        evoke
        clarify
        confess
        pray
        tolerate
        envy
        revenge
        depart
        overtake
        invade
        penetrate
        enclose
        leak
        flush
        sparkle
        erupt
        dye
        halt
        suspend
        surpass
        steer
        navigate
        contradict
        contend
        dissolve
        strive
        legacy
        rumor
        verse
        manuscript
        script
        prose
        headline
        diameter
        vacuum
        flame
        moisture
        erosion
        peninsula
        suicide
        sin
        taboo
        rage
        greed
        boredom
        misery
        plague
        orphan
        liver
        trail
        aisle
        laundry
        merchandise
        bargain
        revenue
        deficit
        amateur
        undergraduate
        ambassador
        warrior
        warfare
        botany
        anthropology
        ideology
        voluntary
        spontaneous
        deliberate
        conspicuous
        transparent
        superficial
        hollow
        peculiar
        partial
        neat
        dim
        alternate
        commonplace
        jealous
        hostile
        ripe
        pregnant
        fertile
        fierce
        drastic
        immense
        supreme
        excel
        swell
        bounce
        roam
        stray
        emigrate
        mutter
        murmur
        chuckle
        choke
        frown
        roar
        shiver
        tremble
        shave
        misunderstand
        soothe
        lure
        mock
        tease
        despise
        disregard
        betray
        aspire
        seize
        fetch
        rub
        flap
        plunge
        insert
        dispose
        withstand
        hinder
        resume
        unify
        staple
        soybean
        bud
        vegetation
        limb
        wrinkle
        sentiment
        grief
        curse
        torture
        mercy
        coward
        predecessor
        psychiatrist
        thesis
        diabetes
        mutation
        bullet
        cluster
        shield
        gear
        vessel
        tactics
        breakdown
        reunion
        knot
        probe
        radiation
        tablet
        vapor
        thermometer
        signature
        triangle
        geometry
        feat
        applause
        glory
        diligent
        earnest
        loyal
        stubborn
        rigid
        stiff
        timid
        idle
        dumb
        obese
        disabled
        clumsy
        punctual
        absurd
        uneasy
        nasty
        naughty
        tidy
        decisive
        upright
        vertical
        gloomy
        obscure
        antique
        sole
        sheer
        marvelous
        splendid
        cherish
        nourish
        hatch
        enlarge
        furnish
        indulge
        surrender
        kneel
        stumble
        wither
        creep
        ache
        await
        foresee
        illuminate
        dread
        depict
        signify
        swear
        dictate
        recite
        enroll
        execute
        fake
        disguise
        stain
        bind
        slap
        omit
        grind
        undermine
        bankrupt
        extinguish
        mend
        congratulate
        certificate
        encyclopedia
        biography
        master
        rhyme
        means
        mold
        scope
        bulk
        trifle
        pill
        dose
        vein
        odor
        pilgrim
        deed
        carriage
        mischief
        slaughter
        haste
        thirst
        monarchy
        reign
        heir
        pardon
        legislation
        cabinet
        ward
        surplus
        arithmetic
        mercury
        monopoly
        friction
        collision
        fusion
        breakthrough
        spectacle
        eminent
        notable
        notorious
        compulsory
        liable
        inclined
        static
        infinite
        eternal
        acute
        abrupt
        swift
        faint
        tender
        humid
        damp
        rotten
        sour
        sore
        savage
        crude
        approximate
        intermediate
        vocational
        masculine
        feminine
        superfluous
        utmost
        contemplate
        ponder
        meditate
        conceive
        speculate
        presume
        proclaim
        disclose
        pledge
        exclaim
        subscribe
        mourn
        resent
        lament
        pant
        suck
        soak
        render
        rotate
        pierce
        carve
        divert
        expel
        assault
        intrude
        addict
        coincide
        ascend
        surge
        evaporate
        expire
        ferment
        merge
        erect
        bless
        prestige
        aristocracy
        statesman
        senator
        creed
        vigor
        dismay
        melancholy
        agony
        anguish
        conscience
        contempt
        scorn
        apathy
        textile
        symmetry
        verge
        cavity
        bribe
        riot
        exile
        archaeology
        specimen
        ornament
        apparatus
        flaw
        eclipse
        astronomy
        aviation
        velocity
        congestion
        questionnaire
        parasite
        personnel
        advent
        token
        premium
        discreet
        wary
        grim
        solemn
        skeptical
        dubious
        vain
        reckless
        ruthless
        eloquent
        furious
        weary
        pessimistic
        cynical
        wicked
        singular
        weird
        literal
        explicit
        implicit
        slender
        gross
        ultraviolet
        spatial
        vacant
        spacious
        ample
        affluent
        infer
        discern
        allege
        ascribe
        prescribe
        comply
        abide
        plead
        preach
        intrigue
        reconcile
        intervene
        restrain
        humiliate
        reproach
        condemn
        defy
        revolt
        impair
        inflict
        degrade
        deteriorate
        corrupt
        contaminate
        oppress
        thrust
        embark
        inspect
        summon
        testify
        persecute
        coerce
        unleash
        emacipate
        endow
        scrutiny
        analogy
        preoccupation
        retrospect
        conceit
        fallacy
        hypocrisy
        nuisance
        delinquency
        hostage
        lawsuit
        attorney
        warrant
        testimony
        verdict
        sanction
        superstition
        folklore
        anecdote
        rhetoric
        stall
        segment
        synthesis
        cohesion
        heredity
        catastrophe
        plight
        solitude
        ordeal
        tyranny
        censorship
        hygiene
        doctrine
        diplomacy
        entity
        sovereign
        authentic
        legitimate
        intelligible
        inherent
        ingenious
        intricate
        homogeneous
        monotonous
        incessant
        perpetual
        imminent
        plausible
        arbitrary
        preliminary
        deficient
        subordinate
        feudal
        obsolete
        mortal
        monetary
        extravagant
        dizzy
        juvenile
        anonymous
        compatible
        ubiquitous
        divine
        sober
        zealous
    """.trimIndent().split("\n")
}